# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
ar1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
ar2 = np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
ar3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [5]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
ar1.shape, ar1.ndim, ar1.dtype, type(ar1)

((3,), 1, dtype('int32'), numpy.ndarray)

In [6]:
# Attributes of 2-dimensional array
ar2.shape, ar2.ndim, ar2.dtype, type(ar2)

((2, 3), 2, dtype('int32'), numpy.ndarray)

In [7]:
# Attributes of 3-dimensional array
ar3.shape, ar3.ndim, ar3.dtype, type(ar3)

((2, 2, 3), 3, dtype('int32'), numpy.ndarray)

In [8]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
ar1_pd = pd.DataFrame(ar1)

In [10]:
# Create an array of shape (10, 2) with only ones
arr_1 = np.random.random(size=(10,2))
arr_1

array([[0.84351791, 0.31028339],
       [0.06746249, 0.64698768],
       [0.90252843, 0.88099699],
       [0.85572161, 0.56826546],
       [0.46777237, 0.68542165],
       [0.84058956, 0.49417447],
       [0.54560485, 0.26044975],
       [0.78917558, 0.56117759],
       [0.30790139, 0.10129802],
       [0.67250783, 0.17540303]])

In [11]:
# Create an array of shape (7, 2, 3) of only zeros
arr_2 = np.random.random(size=(7,2,3))
arr_2

array([[[0.17143929, 0.21019517, 0.05371282],
        [0.84815295, 0.22424677, 0.7416729 ]],

       [[0.84680875, 0.43628058, 0.92783106],
        [0.08315027, 0.91667696, 0.09868146]],

       [[0.07798682, 0.0086294 , 0.56783814],
        [0.45427817, 0.15736969, 0.22567628]],

       [[0.87353529, 0.86399624, 0.99429633],
        [0.70169781, 0.27838473, 0.62155174]],

       [[0.76375248, 0.93049309, 0.36386657],
        [0.56047979, 0.47726413, 0.80309303]],

       [[0.89731502, 0.00847347, 0.52544717],
        [0.31189923, 0.83003571, 0.94135962]],

       [[0.63637005, 0.85130036, 0.3884624 ],
        [0.35871718, 0.9098304 , 0.74432534]]])

In [12]:
# Create an array within a range of 0 and 100 with step 3
arr_3 = np.arange(0,100,3)
arr_3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [13]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(10,size=(7,2))

array([[8, 2],
       [6, 8],
       [7, 8],
       [7, 9],
       [7, 7],
       [0, 0],
       [9, 4]])

In [14]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random(size=[3,5])

array([[0.28526703, 0.37223581, 0.58231016, 0.70941145, 0.60961719],
       [0.12791211, 0.94934214, 0.22022357, 0.42219458, 0.18228377],
       [0.21018196, 0.15503747, 0.40570202, 0.63801363, 0.70552281]])

In [15]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(10,size=[4,6])

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [16]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rand_var = np.random.randint(1,10,size=[3,7])

# Find the unique numbers in the array you just created
np.unique(rand_var)

array([1, 2, 3, 4, 5, 7, 9])

In [17]:
# Find the 0'th index of the latest array you created
rand_var[0]

array([9, 1, 3, 7, 4, 9, 3])

In [18]:
# Get the first 2 rows of latest array you created
rand_var[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [19]:
# Get the first 2 values of the first 2 rows of the latest array
rand_var[:2,:2]

array([[9, 1],
       [5, 3]])

In [22]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rand_var2 = np.random.randint(10,size=[3,5])
rand_var3 = np.ones([3,5])

In [23]:
# Add the two arrays together
rand_var2 + rand_var3

array([[1., 9., 7., 9., 8.],
       [1., 8., 8., 3., 1.],
       [8., 3., 3., 1., 5.]])

In [28]:
# Create another array of ones of shape (5, 3)
rand_zero = np.ones([5,3])

In [29]:
# Try add the array of ones and the other most recent array together
rand_var2 + rand_zero.T

array([[1., 9., 7., 9., 8.],
       [1., 8., 8., 3., 1.],
       [8., 3., 3., 1., 5.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [30]:
# Create another array of ones of shape (3, 5)
rand_ones_2 = np.ones([3,5])

In [31]:
# Subtract the new array of ones from the other most recent array
rand_var2 - rand_ones_2

array([[-1.,  7.,  5.,  7.,  6.],
       [-1.,  6.,  6.,  1., -1.],
       [ 6.,  1.,  1., -1.,  3.]])

In [32]:
# Multiply the ones array with the latest array
rand_var2 * rand_ones_2

array([[0., 8., 6., 8., 7.],
       [0., 7., 7., 2., 0.],
       [7., 2., 2., 0., 4.]])

In [33]:
# Take the latest array to the power of 2 using '**'
rand_var2 ** 2

array([[ 0, 64, 36, 64, 49],
       [ 0, 49, 49,  4,  0],
       [49,  4,  4,  0, 16]], dtype=int32)

In [34]:
# Do the same thing with np.square()
np.square(rand_var2)

array([[ 0, 64, 36, 64, 49],
       [ 0, 49, 49,  4,  0],
       [49,  4,  4,  0, 16]], dtype=int32)

In [35]:
# Find the mean of the latest array using np.mean()
np.mean(rand_var2)

4.0

In [38]:
# Find the maximum of the latest array using np.max()
np.max(rand_var2)

8

In [39]:
# Find the minimum of the latest array using np.min()
np.min(rand_var2)

0

In [40]:
# Find the standard deviation of the latest array
np.std(rand_var2)

3.141125063837266

In [41]:
# Find the variance of the latest array
np.var(rand_var2)

9.866666666666667

In [42]:
# Reshape the latest array to (3, 5, 1)
rand_var2.reshape([3,5,1])

array([[[0],
        [8],
        [6],
        [8],
        [7]],

       [[0],
        [7],
        [7],
        [2],
        [0]],

       [[7],
        [2],
        [2],
        [0],
        [4]]])

In [43]:
# Transpose the latest array
rand_var2.T

array([[0, 0, 7],
       [8, 7, 2],
       [6, 7, 2],
       [8, 2, 0],
       [7, 0, 4]])

What does the transpose do?

In [44]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
ran_1 = np.random.randint(10,size=[3,3])
ran_2 = np.random.randint(10,size=[3,2])

In [45]:
# Perform a dot product on the two newest arrays you created
np.dot(ran_1,ran_2)

array([[114, 141],
       [106, 128],
       [ 49,  46]])

In [46]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
ran_3 = np.random.randint(10,size=[4,3])
ran_4 = np.random.randint(10,size=[4,3])

In [48]:
# Perform a dot product on the two newest arrays you created
np.dot(ran_3,ran_4.T)

array([[ 63,  30,  23,  36],
       [ 58,  18,  34,  36],
       [ 54,  27,  70,  66],
       [124,  60,  90, 102]])

It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [49]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
ran_12 = np.random.randint(10,size=[4,3])
ran_21 = np.random.randint(10,size=[4,3])

In [50]:
# Compare the two arrays with '>'
ran_12 > ran_21

array([[ True,  True, False],
       [ True,  True, False],
       [ True, False,  True],
       [False, False,  True]])

What happens when you compare the arrays with `>`?

In [51]:
# Compare the two arrays with '>='
ran_12 >= ran_21

array([[ True,  True, False],
       [ True,  True, False],
       [ True, False,  True],
       [False,  True,  True]])

In [52]:
# Find which elements of the first array are greater than 7
ran_12[0] > 7

array([False, False, False])

In [53]:
# Which parts of each array are equal? (try using '==')
ran_12 == ran_21

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False]])

In [54]:
# Sort one of the arrays you just created in ascending order
np.sort(ran_12)

array([[1, 2, 5],
       [4, 8, 9],
       [3, 5, 9],
       [6, 6, 8]])

In [55]:
# Sort the indexes of one of the arrays you just created
np.argsort(ran_12)

array([[2, 0, 1],
       [2, 1, 0],
       [1, 0, 2],
       [0, 2, 1]], dtype=int64)

In [58]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(ran_12, axis=0)

array([1, 1, 2], dtype=int64)

In [59]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(ran_12, axis=0)

array([0, 2, 0], dtype=int64)

In [60]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(ran_12, axis=1)

array([1, 0, 2, 1], dtype=int64)

In [62]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(ran_12, axis=1)

array([2, 2, 1, 0], dtype=int64)

In [64]:
# Create an array of normally distributed random numbers
np.random.randn(3,5)

array([[ 0.91488432, -0.66606062, -0.51378749,  0.3013228 , -1.45851692],
       [-0.66273831, -0.14647281, -0.84601702, -0.82248937,  1.08672702],
       [ 1.00498688, -0.44176602, -0.08416509,  1.23701607, -1.42647888]])

In [65]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.