## Numpy Learning and Tricks

In [1]:
import numpy as np

## datatype and attributes

In [2]:
# numpy' main datatype is ndarray

a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3],
               [4,5,6]])

a3 = np.array([[[1,2,3],
                [4,5,6]],
               [[1,2,3],
                [4,5,6]],
               [[1,2,3],
                [4,5,6]]])

In [5]:
type(a2)
type(a3)

numpy.ndarray

In [6]:
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape

(3, 2, 3)

In [9]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

## Create dataframe from ndarray

In [10]:
import pandas as pd

In [11]:
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

# 2. creating arrays

In [12]:
ones = np.ones((2,3),dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [13]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
range_arr = np.arange(2,10,2)
range_arr

array([2, 4, 6, 8])

In [15]:
randomNum = np.random.randint(1,230, size= 10)

In [16]:
randomNum

array([ 70, 110, 139, 173,  67,  25, 211, 217, 223, 138])

In [17]:
ransomNum2 = np.random.random((5,3))
ransomNum2

array([[0.19483982, 0.78614897, 0.64385628],
       [0.60383013, 0.17418142, 0.16068996],
       [0.56421733, 0.21226989, 0.82149009],
       [0.69188775, 0.03799964, 0.16470187],
       [0.76768635, 0.85346669, 0.43077642]])

In [18]:
randomNum3 = np.random.rand(4,6)

In [19]:
randomNum3

array([[0.06577084, 0.85493644, 0.21076234, 0.66930767, 0.41450322,
        0.13141661],
       [0.57703669, 0.00424089, 0.07355233, 0.74171516, 0.8498241 ,
        0.78013199],
       [0.97621941, 0.57366148, 0.25131671, 0.68373446, 0.58683975,
        0.7406701 ],
       [0.59810324, 0.98194035, 0.20792095, 0.3205988 , 0.62265203,
        0.00585763]])

In [20]:
#pseudo random numbers
np.random.seed(seed=4)
randomNum4 = np.random.randint(10,size=(5,3))
randomNum4

array([[7, 5, 1],
       [8, 7, 8],
       [2, 9, 7],
       [7, 7, 9],
       [8, 4, 2]])